# 100_Movie_Details_prep

### Purpose

The purpose of this notebook is to load and prepare the Movie Details dataset. This will include cleaning the dataset and looking for any missing or redundant values. This stage is important to ensure greater accuracy of the later analysis.

### Datasets

The dataset used here is called movie details and was obtained from Kaggle. The link is provided below:

https://www.kaggle.com/stephanerappeneau/350-000-movies-from-themoviedborg/data

# Loading the data

We start by importing all the libraries and loading in the raw dataset.

In [1]:
import pandas as pd
import os.path
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
details = pd.read_csv('../../data/raw/AllMoviesDetailsCleaned.csv', sep=';', engine = 'python')

FileNotFoundError: [Errno 2] No such file or directory: '../../data/raw/AllMoviesDetailsCleaned.csv'

# Data Cleaning and Preperation

The data is really messy at the moment so we need to go through a number of checks and cleaning methods

In [3]:
details.head(5)

,ï»¿id,budget,genres,imdb_id,original_language,original_title,overview,popularity,production_companies,production_countries,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,production_companies_number,production_countries_number,spoken_languages_number
0,2,0,Drama|Crime,tt0094675,fi,Ariel,Taisto Kasurinen is a Finnish coal miner whose...,0.823904,Villealfa Filmproduction Oy,Finland,...,69.0,suomi,Released,NaN,Ariel,7.1,40,2,1,2
1,3,0,Drama|Comedy,tt0092149,fi,Varjoja paratiisissa,"An episode in the life of Nikander, a garbage ...",0.47445,Villealfa Filmproduction Oy,Finland,...,76.0,English,Released,NaN,Shadows in Paradise,7.0,32,1,1,3
2,5,4000000,Crime|Comedy,tt0113101,en,Four Rooms,It's Ted the Bellhop's first night on the job....,1.698,Miramax Films,United States of America,...,98.0,English,Released,Twelve outrageous guests. Four scandalous requ...,Four Rooms,6.5,485,2,1,1
3,6,0,Action|Thriller|Crime,tt0107286,en,Judgment Night,"While racing to a boxing match, Frank, Mike, J...",1.32287,Universal Pictures,Japan,...,110.0,English,Released,Don't move. Don't whisper. Don't even breathe.,Judgment Night,6.5,69,3,2,1
4,8,42000,Documentary,tt0825671,en,Life in Loops (A Megacities RMX),Timo Novotny labels his new project an experim...,0.054716,inLoops,Austria,...,80.0,English,Released,A Megacities remix.,Life in Loops (A Megacities RMX),6.4,4,1,1,5

In [4]:
details.drop(['budget', 'original_language', 'overview', 'production_companies', 'production_countries', 'spoken_languages', 'status', 'tagline', 
              'production_companies_number', 'production_countries_number', 'revenue', 'spoken_languages_number', 'imdb_id',
              'original_title'
             ], axis=1, inplace=True)

We dropped the rows which we were not going to use to decrease the chances data redundancy

In [5]:
details.head(5)

,ï»¿id,genres,popularity,release_date,runtime,title,vote_average,vote_count
0,2,Drama|Crime,0.823904,21/10/1988,69.0,Ariel,7.1,40
1,3,Drama|Comedy,0.47445,16/10/1986,76.0,Shadows in Paradise,7.0,32
2,5,Crime|Comedy,1.698,25/12/1995,98.0,Four Rooms,6.5,485
3,6,Action|Thriller|Crime,1.32287,15/10/1993,110.0,Judgment Night,6.5,69
4,8,Documentary,0.054716,01/01/2006,80.0,Life in Loops (A Megacities RMX),6.4,4

In [6]:
details.rename(columns={'ï»¿id': 'Movie ID', 'genres': 'Genres','popularity': 'Popularity', 
                        'release_date': 'Released','runtime': 'Runtime', 'title': 'Movie Title',
                        'vote_average': 'Average Rating','vote_count': 'Number of Ratings'}, inplace=True)

We decided to rename some columns to make the dataset more descriptive

In [7]:
details.head()

,Movie ID,Genres,Popularity,Released,Runtime,Movie Title,Average Rating,Number of Ratings
0,2,Drama|Crime,0.823904,21/10/1988,69.0,Ariel,7.1,40
1,3,Drama|Comedy,0.47445,16/10/1986,76.0,Shadows in Paradise,7.0,32
2,5,Crime|Comedy,1.698,25/12/1995,98.0,Four Rooms,6.5,485
3,6,Action|Thriller|Crime,1.32287,15/10/1993,110.0,Judgment Night,6.5,69
4,8,Documentary,0.054716,01/01/2006,80.0,Life in Loops (A Megacities RMX),6.4,4

In [8]:
details.shape

(329044, 8)

At the moment the dataset is huge. We need to check for any missing value as they could negatively influence the later stages.

In [9]:
details.isnull().sum()

Movie ID                  0
Genres               121529
Popularity                0
Released              24046
Runtime               36792
Movie Title               1
Average Rating            0
Number of Ratings         0
dtype: int64

In [10]:
details.head(10)

,Movie ID,Genres,Popularity,Released,Runtime,Movie Title,Average Rating,Number of Ratings
0,2,Drama|Crime,0.823904,21/10/1988,69.0,Ariel,7.1,40
1,3,Drama|Comedy,0.47445,16/10/1986,76.0,Shadows in Paradise,7.0,32
2,5,Crime|Comedy,1.698,25/12/1995,98.0,Four Rooms,6.5,485
3,6,Action|Thriller|Crime,1.32287,15/10/1993,110.0,Judgment Night,6.5,69
4,8,Documentary,0.054716,01/01/2006,80.0,Life in Loops (A Megacities RMX),6.4,4
5,9,Drama,0.001647,02/09/2004,15.0,Sunday in August,5.3,2
6,11,Adventure|Action|Science Fiction,10.492614,25/05/1977,121.0,Star Wars,8.0,6168
7,12,Animation|Family,9.915573,30/05/2003,100.0,Finding Nemo,7.6,5531
8,13,Comedy|Drama|Romance,10.351236,06/07/1994,142.0,Forrest Gump,8.2,7204
9,14,Drama,8.191009,15/09/1999,122.0,American Beauty,7.9,2994

We found a lot of missing values, now we will do some checks to see exactly how badly this data could influence our analysis. Some values may just be equal to 0 instead of NaN or null, therefore we will do some checks for them as well.

In [11]:
(details.Genres.isnull()).value_counts()

False    207515
True     121529
Name: Genres, dtype: int64

In [12]:
(details.Popularity == 0).value_counts()

False    329044
Name: Popularity, dtype: int64

In [13]:
(details.Runtime == 0).value_counts()

False    264254
True      64790
Name: Runtime, dtype: int64

In [14]:
(details['Average Rating'] == 0).value_counts()

True     197744
False    131300
Name: Average Rating, dtype: int64

In [15]:
(details['Number of Ratings'] == 0).value_counts()

True     196636
False    132408
Name: Number of Ratings, dtype: int64

In [16]:
details.isnull().sum()

Movie ID                  0
Genres               121529
Popularity                0
Released              24046
Runtime               36792
Movie Title               1
Average Rating            0
Number of Ratings         0
dtype: int64

There is a big number of NaN and 0 values, therefore we decided to drop the rows which include them.

In [17]:
details.dropna(subset=['Genres', 'Released'], inplace = True)

We dropped a lot of rows which lack information, we left the runtime for now

In [18]:
details.isnull().sum()

Movie ID                 0
Genres                   0
Popularity               0
Released                 0
Runtime              20998
Movie Title              0
Average Rating           0
Number of Ratings        0
dtype: int64

In [19]:
details.head(10)

,Movie ID,Genres,Popularity,Released,Runtime,Movie Title,Average Rating,Number of Ratings
0,2,Drama|Crime,0.823904,21/10/1988,69.0,Ariel,7.1,40
1,3,Drama|Comedy,0.47445,16/10/1986,76.0,Shadows in Paradise,7.0,32
2,5,Crime|Comedy,1.698,25/12/1995,98.0,Four Rooms,6.5,485
3,6,Action|Thriller|Crime,1.32287,15/10/1993,110.0,Judgment Night,6.5,69
4,8,Documentary,0.054716,01/01/2006,80.0,Life in Loops (A Megacities RMX),6.4,4
5,9,Drama,0.001647,02/09/2004,15.0,Sunday in August,5.3,2
6,11,Adventure|Action|Science Fiction,10.492614,25/05/1977,121.0,Star Wars,8.0,6168
7,12,Animation|Family,9.915573,30/05/2003,100.0,Finding Nemo,7.6,5531
8,13,Comedy|Drama|Romance,10.351236,06/07/1994,142.0,Forrest Gump,8.2,7204
9,14,Drama,8.191009,15/09/1999,122.0,American Beauty,7.9,2994

We decided to change the format of the Released column to aid later analysis

In [20]:
details['Released'] = pd.to_datetime(details['Released'])

We sorted the data by date to see exactly how far back and forwards it goes

In [21]:
details.sort_values(by='Released')

,Movie ID,Genres,Popularity,Released,Runtime,Movie Title,Average Rating,Number of Ratings
199569,315946,Documentary,0.091601,1874-12-09,1.0,Passage of Venus,6.0,15
115398,194079,Documentary,0.071501,1878-06-14,1.0,Sallie Gardner at a Gallop,6.2,22
293283,426903,Documentary,0.000152,1883-11-19,1.0,Buffalo Running,6.7,3
288521,421316,Documentary,0.000143,1884-01-01,1.0,Descending Stairs and Turning Around,0.0,0
288520,421315,Documentary,0.000143,1884-01-01,2.0,Human Figure in Motion,5.0,1
99061,159897,Documentary,0.158993,1887-08-18,1.0,Man Walking Around a Corner,4.0,15
67440,96882,Documentary,0.001601,1888-01-01,1.0,Accordion Player,4.4,17
217252,335765,Documentary,0.002793,1888-05-31,1.0,Pferd und Reiter Springen Ãœber ein Hindernis,6.7,3
10067,16463,History|Documentary,0.29507,1888-10-14,1.0,Roundhay Garden Scene,6.4,35
10068,16464,Documentary,0.050777,1888-10-15,1.0,Traffic Crossing Leeds Bridge,5.8,24
20553,32406,Documentary,0.01014,1889-01-14,1.0,"Leisurely Pedestrians, Open Topped Buses and H...",6.0,1
21058,33316,Documentary,0.011439,1890-01-01,1.0,London's Trafalgar Square,4.8,8
20646,32571,Comedy,0.005043,1890-11-21,1.0,"Monkeyshines, No. 1",4.4,14
217755,336380,Documentary,0.000485,1891-01-01,1.0,Je Vous Aime,3.5,2
21009,33229,Drama|Documentary,0.000294,1891-01-01,1.0,Dickson Greeting,4.8,12
21060,33318,Documentary|Action,0.020775,1891-04-30,1.0,Men Boxing,3.5,7
71503,104852,Documentary,0.255969,1891-05-01,1.0,Newark Athlete,3.9,14
196512,312452,Documentary,0.000288,1891-11-15,1.0,La Vague,4.0,3
10120,16613,Animation,0.000246,1892-10-27,5.0,The Clown and His Dogs,0.0,0
10126,16622,Animation,0.000926,1892-10-28,15.0,Un bon bock,6.0,1
63395,88013,Comedy|Animation,0.14059,1892-10-28,4.0,Poor Pierrot,6.2,17
10127,16624,Drama,0.105987,1893-05-08,1.0,Blacksmith Scene,5.8,18
234404,356155,Comedy,0.000181,1894-01-01,1.0,"Glenroy Bros., No. 2",5.0,2
95524,152218,Documentary,0.000213,1894-01-01,1.0,The Barbershop,4.9,7
71700,105160,Documentary,0.008865,1894-01-01,1.0,Annabelle Butterfly Dance,5.8,9
96416,154339,Documentary,0.094744,1894-01-01,1.0,Falling Cat,6.0,13
95523,152216,Documentary,0.002424,1894-01-01,1.0,The Cock Fight,6.0,2
112621,189054,Documentary,0.007286,1894-01-01,1.0,"Luis Martinetti, Contortionist",6.5,4
71698,105158,Documentary,0.000258,1894-01-09,1.0,Edison Kinetoscopic Record of a Sneeze,4.7,12
112307,188368,Documentary,0.009357,1894-02-01,1.0,Athlete with Wand,2.7,3
...,...,...,...,...,...,...,...,...
283193,414906,Action|Adventure|Drama,0.527404,2020-05-06,0.0,The Batman,0.0,2
258428,385103,Family|Animation|Comedy|Mystery,0.183629,2020-05-15,0.0,S.C.O.O.B.,0.0,1
270608,399566,Action|Adventure|Drama|Science Fiction|Thriller,0.111858,2020-05-22,0.0,Godzilla vs. Kong,0.0,0
297470,431976,Action,0.002394,2020-06-12,0.0,Vanished,0.0,0
183301,297797,Action|Adventure|Science Fiction,0.467524,2020-07-24,0.0,Green Lantern Corps,0.0,0
291438,424775,Action,0.453715,2020-08-05,0.0,Live Die Repeat and Repeat,0.0,1
217423,335977,Action|Adventure,0.966205,2020-08-07,0.0,Indiana Jones 5,0.0,6
219923,338953,Fantasy,0.641826,2020-11-19,0.0,Fantastic Beasts and Where to Find Them 3,0.0,2
165720,277829,Music|Animation|Adventure|Comedy|Family|Fantasy,0.205682,2020-11-25,0.0,Gigantic,0.0,0
54782,76600,Action|Adventure|Fantasy|Science Fiction,0.990955,2020-12-16,0.0,Avatar 2,0.0,58
303177,438695,Music|Animation|Comedy|Drama|Family,0.006507,2020-12-25,0.0,Sing 2,0.0,0
217422,335976,Thriller|Action|Crime,0.264287,2020-12-31,0.0,Wanted 2,0.0,0
315180,452868,Thriller|Science Fiction|Crime|Action,0.005885,2020-12-31,0.0,Crime of the Century,0.0,0
167905,280239,Horror,0.005717,2020-12-31,0.0,Trick 'r Treat 2,0.0,0
271378,400507,Action|Science Fiction,0.503893,2020-12-31,0.0,X-Force,0.0,0
168379,280773,Documentary,0.002386,2020-12-31,43200.0,AmbiancÃ©,0.0,0
292389,425902,Thriller|Action|Adventure|Science Fiction,0.401635,2020-12-31,0.0,Luna Park,0.0,0
92197,145214,Action|Adventure|Crime,0.308977,2020-12-31,0.0,Splinter Cell,0.0,3
272015,401251,Drama|History,0.042543,2020-12-31,0.0,Thrilla in Manilla,0.0,0
315655,453395,Science Fiction|Fantasy|Action,0.263785,2020-12-31,0.0,Doctor Strange 2,0.0,0
92201,145219,History|Thriller,0.147179,2020-12-31,0.0,The Devil in the White City,0.0,2
258904,385687,Action|Crime|Thriller,1.148093,2021-01-04,0.0,Fast & Furious 10,0.0,3
198910,315162,Comedy|Animation|Family,0.143272,2021-01-12,0.0,Puss in Boots 2: Nine Lives & 40 Thieves,0.0,0
320508,459151,Family|Animation|Comedy,0.381033,2021-03-24,0.0,The Boss Baby 2,0.0,0
60134,83533,Drama|Action|Adventure|Fantasy|Science Fiction,0.351521,2021-12-16,0.0,Avatar 3,0.0,3
265089,392829,Action|Science Fiction|Adventure,0.002486,2022-10-06,0.0,The Realm of Agartha,0.0,1
325942,465558,Science Fiction|Animation,0.007279,2023-01-01,0.0,The Zero Century: Harlock,0.0,0
125479,216527,Action|Adventure|Fantasy|Science Fiction,0.510151,2024-12-19,0.0,Avatar 4,0.0,2
265388,393209,Action|Adventure|Fantasy|Science Fiction,0.132672,2025-12-17,0.0,Avatar 5,0.0,2
325943,465559,Science Fiction|Animation,0.001485,2026-01-01,0.0,The Zero Century: Maetel,0.0,0

We realised that the data includes a lot of movies which are missing some vital information. The dataset also includes a lot of movies which haven't been released yet. We tackled this problem by removing all the rows which had an average rating equal to 0 as the unreleased movies won't have a rating.

In [22]:
(details['Average Rating'] == 0.0).value_counts()

False    107678
True      94793
Name: Average Rating, dtype: int64

In [23]:
details = details[details['Average Rating'] != 0]

In [24]:
(details['Average Rating'] == 0.0).value_counts()

False    107678
Name: Average Rating, dtype: int64

The removal of this data ensured that the data is now accurate. However, there is still some missing information in the runtime section, therefore we will get rid of that as well.

In [74]:
details.sort_values(by='Released')

,Movie ID,Genres,Popularity,Released,Runtime,Movie Title,Average Rating,Number of Ratings
199569,315946,Documentary,0.091601,1874-12-09,1.0,Passage of Venus,6.0,15
115398,194079,Documentary,0.071501,1878-06-14,1.0,Sallie Gardner at a Gallop,6.2,22
293283,426903,Documentary,0.000152,1883-11-19,1.0,Buffalo Running,6.7,3
288520,421315,Documentary,0.000143,1884-01-01,2.0,Human Figure in Motion,5.0,1
99061,159897,Documentary,0.158993,1887-08-18,1.0,Man Walking Around a Corner,4.0,15
67440,96882,Documentary,0.001601,1888-01-01,1.0,Accordion Player,4.4,17
217252,335765,Documentary,0.002793,1888-05-31,1.0,Pferd und Reiter Springen Ãœber ein Hindernis,6.7,3
10067,16463,History|Documentary,0.29507,1888-10-14,1.0,Roundhay Garden Scene,6.4,35
10068,16464,Documentary,0.050777,1888-10-15,1.0,Traffic Crossing Leeds Bridge,5.8,24
20553,32406,Documentary,0.01014,1889-01-14,1.0,"Leisurely Pedestrians, Open Topped Buses and H...",6.0,1
21058,33316,Documentary,0.011439,1890-01-01,1.0,London's Trafalgar Square,4.8,8
20646,32571,Comedy,0.005043,1890-11-21,1.0,"Monkeyshines, No. 1",4.4,14
217755,336380,Documentary,0.000485,1891-01-01,1.0,Je Vous Aime,3.5,2
21009,33229,Drama|Documentary,0.000294,1891-01-01,1.0,Dickson Greeting,4.8,12
21060,33318,Documentary|Action,0.020775,1891-04-30,1.0,Men Boxing,3.5,7
71503,104852,Documentary,0.255969,1891-05-01,1.0,Newark Athlete,3.9,14
196512,312452,Documentary,0.000288,1891-11-15,1.0,La Vague,4.0,3
63395,88013,Comedy|Animation,0.14059,1892-10-28,4.0,Poor Pierrot,6.2,17
10126,16622,Animation,0.000926,1892-10-28,15.0,Un bon bock,6.0,1
10127,16624,Drama,0.105987,1893-05-08,1.0,Blacksmith Scene,5.8,18
96416,154339,Documentary,0.094744,1894-01-01,1.0,Falling Cat,6.0,13
95523,152216,Documentary,0.002424,1894-01-01,1.0,The Cock Fight,6.0,2
95524,152218,Documentary,0.000213,1894-01-01,1.0,The Barbershop,4.9,7
71700,105160,Documentary,0.008865,1894-01-01,1.0,Annabelle Butterfly Dance,5.8,9
234404,356155,Comedy,0.000181,1894-01-01,1.0,"Glenroy Bros., No. 2",5.0,2
112621,189054,Documentary,0.007286,1894-01-01,1.0,"Luis Martinetti, Contortionist",6.5,4
71698,105158,Documentary,0.000258,1894-01-09,1.0,Edison Kinetoscopic Record of a Sneeze,4.7,12
112307,188368,Documentary,0.009357,1894-02-01,1.0,Athlete with Wand,2.7,3
10119,16612,Documentary,0.042673,1894-03-14,1.0,Carmencita,5.0,17
99066,159903,Crime|Comedy,0.00296,1894-04-30,1.0,Chinese Laundry Scene,5.0,2
...,...,...,...,...,...,...,...,...
317453,455461,Action|Crime,0.415651,2017-12-05,122.0,Inayathalam,5.0,1
281104,412363,Comedy|Romance,0.082222,2017-12-05,110.0,The Wedding Plan,6.7,3
324398,463697,Comedy,0.029593,2017-12-05,3.0,Little Fish,10.0,1
319130,457497,Comedy|Drama|History|Romance,0.278102,2017-12-05,140.0,Lahoriye,10.0,3
271949,401164,Drama,0.037783,2017-12-05,88.0,Tracktown,6.0,2
317459,455470,Drama|Romance,0.223227,2017-12-05,117.0,Meri Pyaari Bindu,8.8,5
256608,382883,Drama,1.126182,2017-12-05,80.0,Shepherds and Butchers,7.0,13
289866,422874,Crime|Thriller,0.909827,2017-12-05,86.0,Money,6.0,19
301706,436932,Action|Drama,0.540135,2017-12-05,91.0,Jawbone,6.8,9
277799,408439,Crime|Drama|Thriller,1.179417,2017-12-05,108.0,Hounds of Love,6.2,38
275652,405775,War|Drama|Thriller,0.751209,2017-12-05,81.0,The Wall,6.2,41
275944,406107,Horror|Thriller,1.455399,2017-12-05,99.0,Dead Awake,5.4,14
282272,413762,Drama,0.883654,2017-12-05,83.0,The Levelling,5.6,8
310882,447818,Documentary,0.239935,2017-12-05,106.0,Generation Iron 2,8.4,5
318852,457102,TV Movie|Comedy,0.09663,2017-12-05,NaN,Leichtmatrosen,6.0,1
319028,457380,Comedy,0.118611,2017-12-05,2.0,Elle Fanning's Fan Fantasy,7.0,1
326965,466812,Comedy,0.034463,2017-12-05,19.0,God Complex,1.0,1
317633,455665,Thriller|Drama,0.09172,2017-12-05,82.0,Breaking Point,9.0,1
318953,457268,Drama|Romance,0.09129,2017-12-05,122.0,Ramante Edanthottam,7.0,1
321084,459914,Comedy,0.161329,2017-12-05,NaN,4N1K,8.0,1
220708,339846,Action|Comedy,6.924252,2017-12-05,116.0,Baywatch,5.9,874
285412,417489,Crime|Comedy|Action,0.159927,2017-12-05,0.0,Bon Cop Bad Cop 2,7.0,4
273076,402529,Drama|Music,2.01496,2017-12-06,139.0,All Eyez on Me,6.2,363
322725,461805,Documentary,0.180534,2017-12-06,240.0,The Putin Interviews,8.0,7
309361,446038,Comedy,0.469015,2017-12-07,0.0,Mission Pays Basque,7.6,5
322629,461680,Music,0.279273,2017-12-07,140.0,Falsettos,9.5,1
326411,466173,Family|Comedy|Animation,0.215187,2017-12-07,2.0,Pandas in the Mist: Brochure,5.0,1
294622,428495,Thriller|Drama,0.527033,2017-12-07,106.0,The Nile Hilton Incident,7.7,16
324742,464111,Horror|Science Fiction,0.655798,2017-12-07,23.0,Zygote,7.0,12
326672,466458,Family|Comedy,0.412257,2017-12-07,NaN,Jamel et ses amis au Marrakech du Rire,7.0,2

In [75]:
(details['Runtime'] == 0).value_counts()

False    99224
True      8454
Name: Runtime, dtype: int64

In [76]:
details = details[details['Runtime'] != 0]

In [77]:
(details['Runtime'] == 0).value_counts()

False    99224
Name: Runtime, dtype: int64

In [78]:
details.dropna(subset=['Runtime'], inplace = True)

The data should now be clean, although we have lost a lot of rows.

In [79]:
details.shape

(94207, 8)

In [80]:
details.head()

,Movie ID,Genres,Popularity,Released,Runtime,Movie Title,Average Rating,Number of Ratings
0,2,Drama|Crime,0.823904,1988-10-21,69.0,Ariel,7.1,40
1,3,Drama|Comedy,0.47445,1986-10-16,76.0,Shadows in Paradise,7.0,32
2,5,Crime|Comedy,1.698,1995-12-25,98.0,Four Rooms,6.5,485
3,6,Action|Thriller|Crime,1.32287,1993-10-15,110.0,Judgment Night,6.5,69
4,8,Documentary,0.054716,2006-01-01,80.0,Life in Loops (A Megacities RMX),6.4,4

We realised that the Genre column has a lot of genres separated by '|'. We decided to split these up into separate columns and give them a value '1' if the movie is of that genre and '0' otherwise. This will ensure that the calculations of movie prominence will be easier to make in the analysis stage

In [81]:
details['Drama'] = details['Genres'].str.contains('Drama').apply(lambda x:1 if x else 0)

details['Crime'] = details['Genres'].str.contains('Crime').apply(lambda x:1 if x else 0)

details['Action'] = details['Genres'].str.contains('Action').apply(lambda x:1 if x else 0)

details['Documentary'] = details['Genres'].str.contains('Documentary').apply(lambda x:1 if x else 0)

details['Adventure'] = details['Genres'].str.contains('Adventure').apply(lambda x:1 if x else 0)

details['Animation'] = details['Genres'].str.contains('Animation').apply(lambda x:1 if x else 0)

details['Comedy'] = details['Genres'].str.contains('Comedy').apply(lambda x:1 if x else 0)

details['Mystery'] = details['Genres'].str.contains('Mystery').apply(lambda x:1 if x else 0)

details['Horror'] = details['Genres'].str.contains('Horror').apply(lambda x:1 if x else 0)

details['Western'] = details['Genres'].str.contains('Western').apply(lambda x:1 if x else 0)

details['Science Fiction'] = details['Genres'].str.contains('Science Fiction').apply(lambda x:1 if x else 0)

details['Thriller'] = details['Genres'].str.contains('Thriller').apply(lambda x:1 if x else 0)

details['Romance'] = details['Genres'].str.contains('Romance').apply(lambda x:1 if x else 0)

details['Fantasy'] = details['Genres'].str.contains('Fantasy').apply(lambda x:1 if x else 0)

details['War'] = details['Genres'].str.contains('War').apply(lambda x:1 if x else 0)

details['Family'] = details['Genres'].str.contains('Family').apply(lambda x:1 if x else 0)

details['Music'] = details['Genres'].str.contains('Music').apply(lambda x:1 if x else 0)

details['History'] = details['Genres'].str.contains('History').apply(lambda x:1 if x else 0)

details['TV Movie'] = details['Genres'].str.contains('TV Movie').apply(lambda x:1 if x else 0)

details['Foreign'] = details['Genres'].str.contains('Foreign').apply(lambda x:1 if x else 0)

The Genre column is now split up

In [82]:
details.head()

,Movie ID,Genres,Popularity,Released,Runtime,Movie Title,Average Rating,Number of Ratings,Drama,Crime,...,Science Fiction,Thriller,Romance,Fantasy,War,Family,Music,History,TV Movie,Foreign
0,2,Drama|Crime,0.823904,1988-10-21,69.0,Ariel,7.1,40,1,1,...,0,0,0,0,0,0,0,0,0,0
1,3,Drama|Comedy,0.47445,1986-10-16,76.0,Shadows in Paradise,7.0,32,1,0,...,0,0,0,0,0,0,0,0,0,0
2,5,Crime|Comedy,1.698,1995-12-25,98.0,Four Rooms,6.5,485,0,1,...,0,0,0,0,0,0,0,0,0,0
3,6,Action|Thriller|Crime,1.32287,1993-10-15,110.0,Judgment Night,6.5,69,0,1,...,0,1,0,0,0,0,0,0,0,0
4,8,Documentary,0.054716,2006-01-01,80.0,Life in Loops (A Megacities RMX),6.4,4,0,0,...,0,0,0,0,0,0,0,0,0,0

We decided to look at the types and see if they are okay for every field

In [83]:
details.dtypes

Movie ID                      int64
Genres                       object
Popularity                   object
Released             datetime64[ns]
Runtime                     float64
Movie Title                  object
Average Rating              float64
Number of Ratings             int64
Drama                         int64
Crime                         int64
Action                        int64
Documentary                   int64
Adventure                     int64
Animation                     int64
Comedy                        int64
Mystery                       int64
Horror                        int64
Western                       int64
Science Fiction               int64
Thriller                      int64
Romance                       int64
Fantasy                       int64
War                           int64
Family                        int64
Music                         int64
History                       int64
TV Movie                      int64
Foreign                       int64
dtype: object

The Popularity column is an object, however, it should be a float. Initially we weren't able to do this as some values in the Popularity column included the letter 'E'. To overcome this we decided to get rid of these columns.

In [84]:
details = details[~details['Popularity'].str.contains('E')]

In [85]:
details["Popularity"] = pd.to_numeric(details.Popularity)

Popularity is now a float

In [86]:
details.dtypes

Movie ID                      int64
Genres                       object
Popularity                  float64
Released             datetime64[ns]
Runtime                     float64
Movie Title                  object
Average Rating              float64
Number of Ratings             int64
Drama                         int64
Crime                         int64
Action                        int64
Documentary                   int64
Adventure                     int64
Animation                     int64
Comedy                        int64
Mystery                       int64
Horror                        int64
Western                       int64
Science Fiction               int64
Thriller                      int64
Romance                       int64
Fantasy                       int64
War                           int64
Family                        int64
Music                         int64
History                       int64
TV Movie                      int64
Foreign                       int64
dtype: object

It will be much easier to work with just year and month in the analysis, therefore, we created 2 extra columns based on the movie's release date

In [87]:
details['Year'], details['Month'] = details['Released'].dt.year, details['Released'].dt.month

In [88]:
details.head()

,Movie ID,Genres,Popularity,Released,Runtime,Movie Title,Average Rating,Number of Ratings,Drama,Crime,...,Romance,Fantasy,War,Family,Music,History,TV Movie,Foreign,Year,Month
0,2,Drama|Crime,0.823904,1988-10-21,69.0,Ariel,7.1,40,1,1,...,0,0,0,0,0,0,0,0,1988,10
1,3,Drama|Comedy,0.474450,1986-10-16,76.0,Shadows in Paradise,7.0,32,1,0,...,0,0,0,0,0,0,0,0,1986,10
2,5,Crime|Comedy,1.698000,1995-12-25,98.0,Four Rooms,6.5,485,0,1,...,0,0,0,0,0,0,0,0,1995,12
3,6,Action|Thriller|Crime,1.322870,1993-10-15,110.0,Judgment Night,6.5,69,0,1,...,0,0,0,0,0,0,0,0,1993,10
4,8,Documentary,0.054716,2006-01-01,80.0,Life in Loops (A Megacities RMX),6.4,4,0,0,...,0,0,0,0,0,0,0,0,2006,1

We saved this dataset to a pickle so that we will be able to use it in the other notebooks

In [89]:
details.to_pickle('../../data/processed/Movies_Details.pkl')