In [1]:
import os.path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Ensure the file exists
if  not os.path.exists("AllMoviesCastingRaw.csv"):
    print("Missing dataset file")

In [3]:
casting = pd.read_csv("AllMoviesCastingRaw.csv", sep=';', engine = 'python')

In [4]:
casting.head(5)

,id,actor1_name,actor1_gender,actor2_name,actor2_gender,actor3_name,actor3_gender,actor4_name,actor4_gender,actor5_name,actor5_gender,actor_number,director_name,director_gender,director_number,producer_name,producer_number,screeplay_name,editor_name
0,2,Turo Pajala,0,Susanna Haavisto,0.0,Matti PellonpÃ¤Ã¤,2,Eetu Hilkamo,0,none,0,4,Aki KaurismÃ¤ki,0.0,1,none,0,Aki KaurismÃ¤ki,Raija Talvio
1,3,Matti PellonpÃ¤Ã¤,2,Kati Outinen,1.0,Sakari Kuosmanen,2,Esko Nikkari,2,Kylli KÃ¶ngÃ¤s,0,7,Aki KaurismÃ¤ki,0.0,1,Mika KaurismÃ¤ki,1,Aki KaurismÃ¤ki,Raija Talvio
2,5,Tim Roth,2,Antonio Banderas,2.0,Jennifer Beals,1,Madonna,1,Marisa Tomei,1,24,Allison Anders,1.0,4,Lawrence Bender,1,none,Margaret Goodspeed
3,6,Emilio Estevez,2,Cuba Gooding Jr.,2.0,Denis Leary,2,Jeremy Piven,2,Peter Greene,2,15,Stephen Hopkins,2.0,1,Gene Levy,1,Lewis Colick,Tim Wellburn
4,8,none,0,none,0.0,none,0,none,0,none,0,0,Timo Novotny,0.0,1,Timo Novotny,2,Michael Glawogger,Timo Novotny

In [5]:
casting.actor1_gender.replace([0, 1, 2], ['Unknown', 'Female', 'Male'], inplace=True)
casting.actor2_gender.replace([0, 1, 2], ['Unknown', 'Female', 'Male'], inplace=True)
casting.actor3_gender.replace([0, 1, 2], ['Unknown', 'Female', 'Male'], inplace=True)
casting.actor4_gender.replace([0, 1, 2], ['Unknown', 'Female', 'Male'], inplace=True)
casting.actor5_gender.replace([0, 1, 2], ['Unknown', 'Female', 'Male'], inplace=True)
casting.director_gender.replace([0, 1, 2], ['Unknown', 'Female', 'Male'], inplace=True)

In [6]:
casting.head(5)

,id,actor1_name,actor1_gender,actor2_name,actor2_gender,actor3_name,actor3_gender,actor4_name,actor4_gender,actor5_name,actor5_gender,actor_number,director_name,director_gender,director_number,producer_name,producer_number,screeplay_name,editor_name
0,2,Turo Pajala,Unknown,Susanna Haavisto,Unknown,Matti PellonpÃ¤Ã¤,Male,Eetu Hilkamo,Unknown,none,Unknown,4,Aki KaurismÃ¤ki,Unknown,1,none,0,Aki KaurismÃ¤ki,Raija Talvio
1,3,Matti PellonpÃ¤Ã¤,Male,Kati Outinen,Female,Sakari Kuosmanen,Male,Esko Nikkari,Male,Kylli KÃ¶ngÃ¤s,Unknown,7,Aki KaurismÃ¤ki,Unknown,1,Mika KaurismÃ¤ki,1,Aki KaurismÃ¤ki,Raija Talvio
2,5,Tim Roth,Male,Antonio Banderas,Male,Jennifer Beals,Female,Madonna,Female,Marisa Tomei,Female,24,Allison Anders,Female,4,Lawrence Bender,1,none,Margaret Goodspeed
3,6,Emilio Estevez,Male,Cuba Gooding Jr.,Male,Denis Leary,Male,Jeremy Piven,Male,Peter Greene,Male,15,Stephen Hopkins,Male,1,Gene Levy,1,Lewis Colick,Tim Wellburn
4,8,none,Unknown,none,Unknown,none,Unknown,none,Unknown,none,Unknown,0,Timo Novotny,Unknown,1,Timo Novotny,2,Michael Glawogger,Timo Novotny

In [7]:
casting.drop(['actor_number', 'director_number', 'producer_name', 'producer_number', 'screeplay_name', 'editor_name'
             ], axis=1, inplace=True)

In [8]:
casting.head(5)

,id,actor1_name,actor1_gender,actor2_name,actor2_gender,actor3_name,actor3_gender,actor4_name,actor4_gender,actor5_name,actor5_gender,director_name,director_gender
0,2,Turo Pajala,Unknown,Susanna Haavisto,Unknown,Matti PellonpÃ¤Ã¤,Male,Eetu Hilkamo,Unknown,none,Unknown,Aki KaurismÃ¤ki,Unknown
1,3,Matti PellonpÃ¤Ã¤,Male,Kati Outinen,Female,Sakari Kuosmanen,Male,Esko Nikkari,Male,Kylli KÃ¶ngÃ¤s,Unknown,Aki KaurismÃ¤ki,Unknown
2,5,Tim Roth,Male,Antonio Banderas,Male,Jennifer Beals,Female,Madonna,Female,Marisa Tomei,Female,Allison Anders,Female
3,6,Emilio Estevez,Male,Cuba Gooding Jr.,Male,Denis Leary,Male,Jeremy Piven,Male,Peter Greene,Male,Stephen Hopkins,Male
4,8,none,Unknown,none,Unknown,none,Unknown,none,Unknown,none,Unknown,Timo Novotny,Unknown

In [9]:
casting.rename(columns={'id': 'ID','actor1_name': 'Actor 1', 'actor1_gender': 'Actor 1 Gender', 'actor2_name': 'Actor 2',
                        'actor2_gender': 'Actor 2 Gender', 'actor3_name': 'Actor 3', 'actor3_gender': 'Actor 3 Gender',
                        'actor4_name': 'Actor 4', 'actor4_gender': 'Actor 4 Gender', 'actor5_name': 'Actor 5', 
                        'actor5_gender': 'Actor 5 Gender','director_name': 'Director', 'director_gender': 'Director Gender'
                       }, inplace=True)

In [10]:
casting.head(10)

,ID,Actor 1,Actor 1 Gender,Actor 2,Actor 2 Gender,Actor 3,Actor 3 Gender,Actor 4,Actor 4 Gender,Actor 5,Actor 5 Gender,Director,Director Gender
0,2,Turo Pajala,Unknown,Susanna Haavisto,Unknown,Matti PellonpÃ¤Ã¤,Male,Eetu Hilkamo,Unknown,none,Unknown,Aki KaurismÃ¤ki,Unknown
1,3,Matti PellonpÃ¤Ã¤,Male,Kati Outinen,Female,Sakari Kuosmanen,Male,Esko Nikkari,Male,Kylli KÃ¶ngÃ¤s,Unknown,Aki KaurismÃ¤ki,Unknown
2,5,Tim Roth,Male,Antonio Banderas,Male,Jennifer Beals,Female,Madonna,Female,Marisa Tomei,Female,Allison Anders,Female
3,6,Emilio Estevez,Male,Cuba Gooding Jr.,Male,Denis Leary,Male,Jeremy Piven,Male,Peter Greene,Male,Stephen Hopkins,Male
4,8,none,Unknown,none,Unknown,none,Unknown,none,Unknown,none,Unknown,Timo Novotny,Unknown
5,9,Rita Lengyel,Female,Milton Welsh,Male,none,Unknown,none,Unknown,none,Unknown,Marc Meyer,Unknown
6,11,Mark Hamill,Male,Harrison Ford,Male,Carrie Fisher,Female,Peter Cushing,Male,Alec Guinness,Male,George Lucas,Male
7,12,Albert Brooks,Male,Ellen DeGeneres,Female,Alexander Gould,Male,Willem Dafoe,Male,Brad Garrett,Male,Andrew Stanton,Male
8,13,Tom Hanks,Male,Robin Wright,Female,Gary Sinise,Male,Mykelti Williamson,Male,Sally Field,Female,Robert Zemeckis,Male
9,14,Kevin Spacey,Male,Annette Bening,Female,Thora Birch,Female,Wes Bentley,Male,Mena Suvari,Female,Sam Mendes,Male

In [ ]:
casting.shape

In [ ]:
casting.isnull().sum()

In [ ]:
casting.to_pickle("Movies_Casting.pkl")
casting.shape

In [ ]:
casting = pd.read_pickle("Movies_Casting.pkl")

In [ ]:
casting.shape

In [ ]:
casting['Actor 1 Gender'].value_counts().plot.bar()

In [ ]:
casting['Director'].value_counts()